name: Snake Game

on:
  # Executar automaticamente a cada 24 horas
  schedule:
    - cron: "0 */24 * * *"

  # Permitir a execução manual do job a qualquer momento
  workflow_dispatch:

  # Executar em cada push na branch master
  push:
    branches:
      - master

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2

      - name: Gerar github-contribution-grid-snake.svg
        uses: aelassas/snk@master
        with:
          github_user_name: camilajullyane
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Commit e push das alterações
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add dist/github-contribution-grid-snake.svg
          git commit -m "Atualizar github-contribution-grid-snake.svg"
          git push

